  File "10k.py", line 6735, in executeOp
    line.sendMessage(to, 'เกิดข้อผิดพลาด\n' + str(error))
  File "/root/10k/LineAPI/linepy/talk.py", line 10, in checkLogin
    return func(*args, **kwargs)
  File "/root/10k/LineAPI/linepy/talk.py", line 111, in sendMessage
    return self.talk.sendMessage(self._messageReq[to], msg)
  File "/usr/local/lib/python3.6/dist-packages/akad/TalkService.py", line 8145, in sendMessage
    return self.recv_sendMessage()
  File "/usr/local/lib/python3.6/dist-packages/akad/TalkService.py", line 8170, in recv_sendMessage
    raise result.e
